#! /bin/bash

###
# ============LICENSE_START=======================================================
# ONAP POLICY
# ================================================================================
# Copyright (C) 2020 AT&T Intellectual Property. All rights reserved.
# ================================================================================
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============LICENSE_END=========================================================
##

for actor in AAI GUARD SO SDNC VFC
do
    if [[ ${actor} == AAI ]]; then
        AAI_PROP_FILE=${POLICY_HOME}/config/${actor}-http-client.properties
        if [[ -f ${AAI_PROP_FILE}.ofc ]]; then
            mv $AAI_PROP_FILE.ofc $AAI_PROP_FILE
        fi
    fi
    if [[ ${actor} == SO ]]; then
        SO_PROP_FILE=${POLICY_HOME}/config/${actor}-http-client.properties
        if [[ -f ${SO_PROP_FILE}.ofc ]]; then
            mv $SO_PROP_FILE.ofc $SO_PROP_FILE
        fi
    fi
    if [[ ${actor} == SDNC ]]; then
        SDNC_PROP_FILE=${POLICY_HOME}/config/${actor}-http-client.properties
        if [[ -f ${SDNC_PROP_FILE}.ofc ]]; then
            mv $SDNC_PROP_FILE.ofc $SDNC_PROP_FILE
        fi
    fi
    if [[ ${actor} == VFC ]]; then
        VFC_PROP_FILE=${POLICY_HOME}/config/${actor}-http-client.properties
        if [[ -f ${VFC_PROP_FILE}.ofc ]]; then
            mv $VFC_PROP_FILE.ofc $VFC_PROP_FILE
        fi
    fi
    if [[ ${actor} == GUARD ]]; then
        GUARD_PROP_FILE=${POLICY_HOME}/config/${actor}-http-client.properties
        if [[ -f ${GUARD_PROP_FILE}.ofc ]]; then
            mv $GUARD_PROP_FILE.ofc $GUARD_PROP_FILE
        fi
    fi
done