#! /bin/bash

###
# ============LICENSE_START=======================================================
# ONAP POLICY
# ================================================================================
# Copyright (C) 2020 AT&T Intellectual Property. All rights reserved.
# ================================================================================
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============LICENSE_END=========================================================
##

for actor in AAI SO SDNC VFC GUARD
do
    FILE=${POLICY_HOME}/config/${actor}-http-client.properties
    if [[ -f ${FILE} && ${actor} != GUARD ]]; then
        case ${actor} in
        AAI)
            PORT=6666
            ;;
        SO)
            PORT=6667
            ;;
        VFC)
            PORT=6668
            ;;
        SDNC)
            PORT=6670
            ;;
        esac
        sed -i.ofc \
        -e "s/^http.client.services.${actor}.https[\s\t]*=.*/http.client.services.${actor}.https=false/g" \
        -e "s/^http.client.services.${actor}.host[\s\t]*=.*/http.client.services.${actor}.host=localhost/g" \
        -e "s/^http.client.services.${actor}.userName[\s\t]*=.*/http.client.services.${actor}.userName=policy/g" \
        -e "s/^http.client.services.${actor}.password[\s\t]*=.*/http.client.services.${actor}.password=policy/g" \
        -e "s/^http.client.services.${actor}.port[\s\t]*=.*/http.client.services.${actor}.port=${PORT}/g" \
        -e "s/^http.client.services.${actor}.contextUriPath[\s\t]*=.*/http.client.services.${actor}.contextUriPath=/g" \
        ${FILE}
    else
        sed -i.ofc \
        -e "s/^http.client.services.${actor}.https[\s\t]*=.*/http.client.services.${actor}.https=false/g" \
        -e "s/^http.client.services.${actor}.host[\s\t]*=.*/http.client.services.${actor}.host=localhost/g" \
        -e "s/^http.client.services.${actor}.port[\s\t]*=.*/http.client.services.${actor}.port=6669/g" \
        -e "s!^http.client.services.${actor}.contextUriPath[\s\t]*=.*!http.client.services.${actor}.contextUriPath=policy/pdpx/v1/!g" \
        -e "s/^http.client.services.${actor}.userName[\s\t]*=.*/http.client.services.${actor}.userName=/g" \
        -e "s/^http.client.services.${actor}.password[\s\t]*=.*/http.client.services.${actor}.password=/g" \
        ${FILE}
    fi
done
